name: go-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.20
      - name: Install latest nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Set up WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: test
        run: make go-test