name: rust-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
            rust-version: stable
      - name: test
        run: make rust-test